# k8s/frontend.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: velocity-frontend
  namespace: frontend
spec:
  replicas: 2
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: velocity-frontend
  template:
    metadata:
      labels:
        app: velocity-frontend
    spec:
      containers:
        - name: velocity-frontend
          image: ghcr.io/builderwire-inc/velocity-frontend:main
          ports:
            - name: http
              containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 20
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: velocity-frontend
  namespace: frontend
  labels:
    app: velocity-frontend
spec:
  selector:
    app: velocity-frontend
  ports:
    - name: http
      port: 80
      targetPort: http
  type: ClusterIP
